/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.mavenproyecto1;

import Clases.AggOrden;
import Clases.Conectar;
import java.awt.CardLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.CallableStatement;
import java.sql.Connection;
import java.text.SimpleDateFormat;
import javax.swing.DefaultListModel;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author 1
 */
public class Prueba02 extends javax.swing.JFrame implements ActionListener {
        Pb01 Pb01 = new  Pb01();
        Pb02 Pb02 = new  Pb02();
        Pb03 Pb03 = new  Pb03();
        Pb04 Pb04 = new  Pb04();
        PanelM panelM = new PanelM();
        PanelM2 panelM2 = new PanelM2();
        PanelM3 panelM3 = new PanelM3();
        
        private final AggOrden orden;
     Conectar conexion;
        
        DefaultTableModel m;
        static double total=0.0;
       
        
        CardLayout vista;
        public static DefaultTableModel model2;
    /**
     * Creates new form ProyectoNuevo01
     */
    public Prueba02() {
        initComponents();
        
        this.setLocationRelativeTo(this);
        orden = new AggOrden();
        
//      contenedor.add(panelM);
//        deshabilitar();
      
      PanelDeslizamiento.setVisible(false);
      PanelTotal.setVisible(false);
      btnAnterior.setEnabled(false);
//       btnSiguiente.setEnabled(true);
      btnSiguiente.addActionListener(this);
      btnAnterior.addActionListener(this);
    
//      deshabilitarBotones();

model2 = new DefaultTableModel();
    model2.addColumn("Nombre");
    model2.addColumn("Precio");
    TablaContenido.setModel(model2);
      
//      propiedadesTabla();
      
    vista = (CardLayout) contenedor.getLayout();
    }
    
//    private void deshabilitar(){
//        if(Pb01.isVisible()){
//            PanelDeslizamiento.setVisible(true);
//            panelM.setVisible(false);
//            panelM2.setVisible(false);
//            panelM3.setVisible(false);
//            PanelTotal.setVisible(true);
//        }else if(panelM.isVisible()){
//              PanelDeslizamiento.setVisible(false);
//            Pb01.setVisible(false);
//            panelM2.setVisible(false);
//            panelM3.setVisible(false);
//            PanelTotal.setVisible(false);
//        }else if(panelM2.isVisible()){
//              PanelDeslizamiento.setVisible(false);
//            panelM.setVisible(false);
//            Pb01.setVisible(false);
//            panelM3.setVisible(false);
//            PanelTotal.setVisible(false);
//        }else if (panelM3.isVisible()){
//               PanelDeslizamiento.setVisible(false);
//            panelM.setVisible(false);
//            panelM2.setVisible(false);
//            Pb01.setVisible(false);
//            PanelTotal.setVisible(false);
//        }
//        
//    }
    
 private void propiedadesTabla(){
//       String titulos[] = {"Nombre","Precio"};
//       DefaultTableModel prop = new DefaultTableModel(null,titulos);
//       TablaContenido.setModel(prop);

    
   }
 private void calcular(){
     double suma = 0;
  
     for(int i = 0; i<TablaContenido.getRowCount(); i++){
         double renglon;
         
         renglon = Double.parseDouble(TablaContenido.getValueAt(i, 1).toString());
         suma = suma +renglon;
         
         txtTotal.setText(String.valueOf(suma));
         
     }
     
 }
 
  private void resta(){
     double resta = 0;
  
     for(int i = 0; i<TablaContenido.getRowCount(); i++){
         double renglon;
         
         renglon = Double.parseDouble(TablaContenido.getValueAt(i, 1).toString());
         resta = renglon-resta;
         
         txtTotal.setText(String.valueOf(resta));
         
     }
     
 }
 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelTotal = new javax.swing.JPanel();
        PanelEnvioDatos = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txtTotal = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtMesa = new javax.swing.JTextField();
        btnAceptar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        TablaContenido = new javax.swing.JTable();
        jDfech = new com.toedter.calendar.JDateChooser();
        PanelDeslizamiento = new javax.swing.JPanel();
        btnSiguiente = new javax.swing.JButton();
        btnAnterior = new javax.swing.JButton();
        PanelOptions = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnPrimero = new javax.swing.JButton();
        btnSegundo = new javax.swing.JButton();
        btnTercero = new javax.swing.JButton();
        btnCuarto = new javax.swing.JButton();
        Secundario = new javax.swing.JPanel();
        contenedor = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(240, 174, 31));

        PanelTotal.setBackground(new java.awt.Color(255, 255, 255));
        PanelTotal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));
        PanelTotal.setLayout(new java.awt.BorderLayout());

        PanelEnvioDatos.setBackground(new java.awt.Color(0, 0, 0));
        PanelEnvioDatos.setLayout(new java.awt.GridLayout(1, 0));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Total");
        PanelEnvioDatos.add(jLabel4);

        txtTotal.setBackground(new java.awt.Color(0, 204, 153));
        txtTotal.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                txtTotalMouseMoved(evt);
            }
        });
        txtTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotalActionPerformed(evt);
            }
        });
        PanelEnvioDatos.add(txtTotal);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("No. de Mesa");
        PanelEnvioDatos.add(jLabel3);

        txtMesa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMesaActionPerformed(evt);
            }
        });
        PanelEnvioDatos.add(txtMesa);

        btnAceptar.setBackground(new java.awt.Color(0, 0, 0));
        btnAceptar.setForeground(new java.awt.Color(255, 255, 255));
        btnAceptar.setText("Aceptar");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });
        PanelEnvioDatos.add(btnAceptar);

        btnEliminar.setBackground(new java.awt.Color(0, 0, 0));
        btnEliminar.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnEliminar.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        PanelEnvioDatos.add(btnEliminar);

        PanelTotal.add(PanelEnvioDatos, java.awt.BorderLayout.PAGE_END);

        TablaContenido.setBackground(new java.awt.Color(51, 51, 51));
        TablaContenido.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        TablaContenido.setForeground(new java.awt.Color(255, 255, 255));
        TablaContenido.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2"
            }
        ));
        jScrollPane2.setViewportView(TablaContenido);

        PanelTotal.add(jScrollPane2, java.awt.BorderLayout.LINE_START);

        jDfech.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jDfechMouseClicked(evt);
            }
        });
        PanelTotal.add(jDfech, java.awt.BorderLayout.PAGE_START);

        getContentPane().add(PanelTotal, java.awt.BorderLayout.LINE_END);

        PanelDeslizamiento.setBackground(new java.awt.Color(0, 0, 0));

        btnSiguiente.setBackground(new java.awt.Color(0, 0, 0));
        btnSiguiente.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        btnSiguiente.setForeground(new java.awt.Color(255, 255, 255));
        btnSiguiente.setText("Siguiente");
        PanelDeslizamiento.add(btnSiguiente);

        btnAnterior.setBackground(new java.awt.Color(0, 0, 0));
        btnAnterior.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        btnAnterior.setForeground(new java.awt.Color(255, 255, 255));
        btnAnterior.setText("Anterior");
        btnAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnteriorActionPerformed(evt);
            }
        });
        PanelDeslizamiento.add(btnAnterior);

        getContentPane().add(PanelDeslizamiento, java.awt.BorderLayout.PAGE_END);

        PanelOptions.setBackground(new java.awt.Color(0, 0, 51));
        PanelOptions.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));

        jLabel1.setFont(new java.awt.Font("Odin Rounded", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 255, 255));
        jLabel1.setText("Menú");

        btnPrimero.setBackground(new java.awt.Color(0, 0, 0));
        btnPrimero.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        btnPrimero.setForeground(new java.awt.Color(255, 255, 255));
        btnPrimero.setText("Presentacion");
        btnPrimero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrimeroActionPerformed(evt);
            }
        });

        btnSegundo.setBackground(new java.awt.Color(0, 0, 0));
        btnSegundo.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        btnSegundo.setForeground(new java.awt.Color(255, 255, 255));
        btnSegundo.setText("Opciones");
        btnSegundo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSegundoActionPerformed(evt);
            }
        });

        btnTercero.setBackground(new java.awt.Color(0, 0, 0));
        btnTercero.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        btnTercero.setForeground(new java.awt.Color(255, 255, 255));
        btnTercero.setText("¿Quienes Somos?");
        btnTercero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTerceroActionPerformed(evt);
            }
        });

        btnCuarto.setBackground(new java.awt.Color(0, 0, 0));
        btnCuarto.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        btnCuarto.setForeground(new java.awt.Color(255, 255, 255));
        btnCuarto.setText("Agradecimientos");
        btnCuarto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCuartoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelOptionsLayout = new javax.swing.GroupLayout(PanelOptions);
        PanelOptions.setLayout(PanelOptionsLayout);
        PanelOptionsLayout.setHorizontalGroup(
            PanelOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnPrimero, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnSegundo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnTercero, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(PanelOptionsLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(PanelOptionsLayout.createSequentialGroup()
                .addComponent(btnCuarto, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        PanelOptionsLayout.setVerticalGroup(
            PanelOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelOptionsLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(btnPrimero, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSegundo, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnTercero, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnCuarto, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(PanelOptions, java.awt.BorderLayout.LINE_START);

        Secundario.setLayout(new java.awt.CardLayout());
        getContentPane().add(Secundario, java.awt.BorderLayout.CENTER);

        contenedor.setBackground(new java.awt.Color(0, 0, 51));
        contenedor.setLayout(new java.awt.CardLayout());
        getContentPane().add(contenedor, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPrimeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrimeroActionPerformed
            contenedor.add(panelM);
            panelM.setVisible(true);
            Pb01.setVisible(false);
            panelM2.setVisible(false);
            panelM3.setVisible(false);
            PanelTotal.setVisible(false);
            contenedor.validate();;
            PanelDeslizamiento.setVisible(false);
    }//GEN-LAST:event_btnPrimeroActionPerformed

    private void btnSegundoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSegundoActionPerformed
            contenedor.add(Pb01);
            Pb01.setVisible(true);
            PanelTotal.setVisible(true);
            PanelDeslizamiento.setVisible(true);
            panelM.setVisible(false);
            panelM2.setVisible(false);
            panelM3.setVisible(false);
            
            contenedor.validate();
            
    }//GEN-LAST:event_btnSegundoActionPerformed

    private void btnAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnteriorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAnteriorActionPerformed

    private void btnTerceroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTerceroActionPerformed
         contenedor.add(panelM2);
            panelM.setVisible(false);
            panelM2.setVisible(true);
            Pb01.setVisible(false);
            panelM3.setVisible(false);
            PanelTotal.setVisible(false);
            PanelDeslizamiento.setVisible(false);
            
            contenedor.validate();;
            
    }//GEN-LAST:event_btnTerceroActionPerformed

    private void btnCuartoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCuartoActionPerformed
        contenedor.add(panelM3);
            panelM.setVisible(false);
            panelM2.setVisible(false);
            panelM3.setVisible(true);
            Pb01.setVisible(false);
            PanelTotal.setVisible(false);
              PanelDeslizamiento.setVisible(false);
            contenedor.validate();;
          
    }//GEN-LAST:event_btnCuartoActionPerformed

    private void txtMesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMesaActionPerformed
        
    }//GEN-LAST:event_txtMesaActionPerformed

    private void txtTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalActionPerformed
        double calcula = 0.0;
        
        int fsel = TablaContenido.getSelectedRow();
        String nombre, precio;
        precio = TablaContenido.getValueAt(fsel, 2).toString();
        
        m = (DefaultTableModel) TablaContenido.getModel();
        calcula = (Double.parseDouble(precio));
        total=total+calcula;
        
        txtTotal.setText(""+total);
        
        calcular();
        
    }//GEN-LAST:event_txtTotalActionPerformed

    private void jDfechMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jDfechMouseClicked
      
    }//GEN-LAST:event_jDfechMouseClicked

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
          int FilaSeleccionada =TablaContenido.getSelectedRow();
           
           if(FilaSeleccionada >= 0){
               String Datos []= new String [2];
               Datos[0]=TablaContenido.getValueAt(FilaSeleccionada, 0).toString();
               Datos[1]=TablaContenido.getValueAt(FilaSeleccionada, 1).toString();
               
              
              model2.removeRow(FilaSeleccionada);
              resta();
           }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        try {
             Conectar cc = new Conectar();
        Connection cone = cc.getConnection();
            for(int i = 0; i<TablaContenido.getRowCount(); i++){
                Connection BD = conexion.getConnection();  
          CallableStatement cs = BD.prepareCall("{call orden (?,?)}");
          cs.setString(1, TablaContenido.getValueAt(i, 0).toString());
          cs.setString(2, TablaContenido.getValueAt(i, 1).toString());
          cs.executeUpdate();
            
            }
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
//          double tot = Double.parseDouble(txtTotal.getText());
//       int mesa = Integer.parseInt(txtMesa.getText());
//       
//       SimpleDateFormat formatoFecha = new SimpleDateFormat("yyyy-MM-dd");
//      String fech = formatoFecha.format(jDfech.getDate());
//      
//      orden.aggOrden2(tot, mesa, fech);
    }//GEN-LAST:event_btnAceptarActionPerformed

    private void txtTotalMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtTotalMouseMoved
        
    }//GEN-LAST:event_txtTotalMouseMoved

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Prueba02.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Prueba02.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Prueba02.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Prueba02.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Prueba02().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelDeslizamiento;
    private javax.swing.JPanel PanelEnvioDatos;
    private javax.swing.JPanel PanelOptions;
    private javax.swing.JPanel PanelTotal;
    private javax.swing.JPanel Secundario;
    public static javax.swing.JTable TablaContenido;
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnAnterior;
    private javax.swing.JButton btnCuarto;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnPrimero;
    private javax.swing.JButton btnSegundo;
    private javax.swing.JButton btnSiguiente;
    private javax.swing.JButton btnTercero;
    private javax.swing.JPanel contenedor;
    private com.toedter.calendar.JDateChooser jDfech;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField txtMesa;
    public static javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent e) {
        Object evt = e.getSource();  
        if(evt.equals(btnAnterior)){
          if(Pb02.isVisible()){
            contenedor.add(Pb01);
            Pb01.setVisible(true);
            Pb02.setVisible(false);
            Pb03.setVisible(false);
            Pb04.setVisible(false);
            btnAnterior.setEnabled(false);
             btnSiguiente.setEnabled(true);
           
          }
          else if(Pb03.isVisible()){
            contenedor.add(Pb02);
            Pb01.setVisible(false);
            Pb02.setVisible(true);
            Pb03.setVisible(false);
            Pb04.setVisible(false);
          }
          else if(Pb04.isVisible()){
            contenedor.add(Pb03);
            Pb01.setVisible(false);
            Pb02.setVisible(false);
            Pb03.setVisible(true);
            Pb04.setVisible(false);
          }
          
          
          contenedor.validate();
//          deshabilitarBotones();
        }
        else if(evt.equals(btnSiguiente)){
              if(Pb01.isVisible()){
            contenedor.add(Pb02);
            Pb01.setVisible(false);
            Pb02.setVisible(true);
            Pb03.setVisible(false);
            Pb04.setVisible(false);
          }
          else if(Pb02.isVisible()){
            contenedor.add(Pb03);
            Pb01.setVisible(false);
            Pb02.setVisible(false);
            Pb03.setVisible(true);
            Pb04.setVisible(false);
          }
          else if(Pb03.isVisible()){
            contenedor.add(Pb04);
            Pb01.setVisible(false);
            Pb02.setVisible(false);
            Pb03.setVisible(false);
            Pb04.setVisible(true);
            
            btnSiguiente.setEnabled(false);
            btnAnterior.setEnabled(true);
          }
              contenedor.validate();
        
                    }
                    
        } 

    }
    
// public DefaultListModel agregaDatos(){
//    DefaultListModel modelo = (DefaultListModel) Lista1.getModel();
//
//}

